#!/bin/sh -e

PECL_NAME=##peclpackagename##
PHP_VERSION=##phpversion##

# Source debconf library.
. /usr/share/debconf/confmodule

db_title "PHP"

for SAPI in apache apache2 cgi cli
do
	# Skip this loop if the config file isn't there (yet).
	if [ -f "/etc/php${PHP_VERSION}/$SAPI/php.ini" ]; then
		db_register php/add_extension php${PHP_VERSION}/extension_${PECL_NAME}_$SAPI

		if grep -q "^[[:space:]]*extension[[:space:]]*=[[:space:]]*${PECL_NAME}\.so" "/etc/php${PHP_VERSION}/$SAPI/php.ini"
		then
			db_set php${PHP_VERSION}/extension_${PECL_NAME}_$SAPI true
		else
			db_set php${PHP_VERSION}/extension_${PECL_NAME}_$SAPI false
		fi

		db_subst php${PHP_VERSION}/extension_${PECL_NAME}_$SAPI extname ${PECL_NAME}
		db_subst php${PHP_VERSION}/extension_${PECL_NAME}_$SAPI sapiconfig $SAPI
		db_subst php${PHP_VERSION}/extension_${PECL_NAME}_$SAPI phpversion ${PHP_VERSION}
		db_input low php${PHP_VERSION}/extension_${PECL_NAME}_$SAPI || true
	fi
done

db_go
