#!/bin/sh

set -e

case "$1" in
    configure)
        if [ -f /usr/share/doc/##packagename##/package.xml -a -x /usr/bin/pear ]; then
            cd /usr/share/doc/##packagename##
            /usr/bin/pear install -r -n package.xml
        fi
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac


#DEBHELPER#

exit 0
