#!/bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [ -x /usr/bin/pear ]; then
            /usr/bin/pear uninstall -r -n ##pearpkgname##
        fi
        ;;

    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
